=== haukex/igbdatatools/loggerdata/metadata.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://squid.igb-berlin.de/igbdatatools/logger_metadata_defs",
	"$comment": "http://json-schema.org/understanding-json-schema/index.html",
	"$defs": {
		"ident":   { "type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]{1,254}$" },
		"colname": { "type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]{1,250}(\\(\\d{1,3}\\))?$" },
		"colobj": {
			"type": "object",
			"$comment": "property types should be the same as in 'columns'",
			"properties": {
				"name": { "$ref": "#/$defs/colname" },
				"unit": { "type": "string", "$comment": "further validation in code" },
				"prc":  { "type": "string", "$comment": "further validation in code" }
			},
			"required": [ "name" ],
			"additionalProperties": false
		}
	},
	"type": "object",
	"properties": {
		"logger_name": { "$ref": "#/$defs/ident" },
		"toa5_env_match": {
			"type": "object",
			"properties": {
				"station_name":  { "type": "string" },
				"logger_model":  { "type": "string" },
				"logger_serial": { "type": "string" },
				"logger_os":     { "type": "string" },
				"program_name":  { "type": "string" },
				"program_sig":   { "type": "string" }
			},
			"minProperties": 1,
			"additionalProperties": false
		},
		"tz": {
			"type": "string",
			"title": "timezone",
			"description": "can be a fixed offset in +HH:MM or -HH:MM format or a time zone name such as UTC or Europe/Berlin"
		},
		"min_datetime": {
			"title": "minimum date/time for this logger",
			"description": "e.g. when the logger was installed",
			"type": "string",
			"pattern": "^\\d{4}-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d(Z|[-+]\\d\\d:\\d\\d)?$"
		},
		"variants": {
			"type": "array",
			"items": { "$ref": "#/$defs/ident" },
			"uniqueItems": true,
			"$comment": "further validation in code"
		},
		"sensors": {
			"type": "object",
			"propertyNames": { "$ref": "#/$defs/ident" },
			"additionalProperties": { "type": "string" },
			"$comment": "further validation in code"
		},
		"tables": {
			"type": "object",
			"propertyNames": { "$ref": "#/$defs/ident" },
			"minProperties": 1,
			"additionalProperties": {
				"type": "object",
				"properties": {
					"prikey": {
						"type": "integer",
						"minimum": 0,
						"description": "The 0-based index into columns of the primary key."
					},
					"columns": {
						"type": "array",
						"items": {
							"type": "object",
							"$comment": "property types should be the same as in 'colobj'",
							"properties": {
								"name":    { "$ref": "#/$defs/colname" },
								"unit":    { "type": "string", "$comment": "further validation in code" },
								"prc":     { "type": "string", "$comment": "further validation in code" },
								"type":    { "type": "string", "$comment": "further validation in code" },
								"var":     { "$ref": "#/$defs/ident", "$comment": "must reference a variant" },
								"plotgrp": { "$ref": "#/$defs/ident" },
								"sens":    { "$ref": "#/$defs/ident", "$comment": "must reference a sensor" },
								"desc":    { "type": "string" }
							},
							"required": [ "name" ],
							"additionalProperties": false
						},
						"minItems": 1
					},
					"mappings": {
						"type": "object",
						"propertyNames": { "$ref": "#/$defs/ident" },
						"additionalProperties": {
							"type": "object",
							"properties": {
								"type": { "enum": ["view"] },
								"map": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"old": { "$ref": "#/$defs/colobj" },
											"new": { "$ref": "#/$defs/colobj" }
										},
										"required": [ "old", "new" ],
										"additionalProperties": false
									},
									"minItems": 1
								}
							},
							"required": [ "type", "map" ],
							"additionalProperties": false
						}
					},
					"$comment": { "type": "string" }
				},
				"required": [ "columns" ],
				"additionalProperties": false
			}
		},
		"$comment": { "type": "string" }
	},
	"required": [ "logger_name", "toa5_env_match", "tables" ],
	"additionalProperties": false
}

=== haukex/igbdatatools/tests/TestLogger.json
{
	"logger_name": "TestLogger",
	"toa5_env_match": {
		"logger_model": "CR1000X",
		"logger_serial": "12342",
		"station_name": "TestLogger"
	},
	"tz": "UTC",
	"min_datetime": "2021-06-18 11:00:00",
	"variants": ["abc", "def"],
	"sensors": {
		"acme42": "Acme Pressure and Humidity Sensor #42",
		"acme532": "Acme Model 532 Air Temperature Sensor"
	},
	"tables": {
		"Daily": {
			"columns": [
				{ "name": "TIMESTAMP",   "unit": "TS",                  "type": "TimestampNoTz" },
				{ "name": "RECORD",      "unit": "RN",                  "type": "NonNegInt"     },
				{ "name": "BattV_Min",   "unit": "Volts", "prc": "Min", "type": "Num(4,2)"      },
				{ "name": "BattV_TMn",                    "prc": "TMn", "type": "TimestampNoTz" },
				{ "name": "PTemp_C_Min", "unit": "Deg C", "prc": "Min", "type": "Num(5,2)",     "plotgrp": "PTemp", "desc": "Panel Temperature Minimum" },
				{ "name": "PTemp_C_TMn",                  "prc": "TMn", "type": "TimestampNoTz" },
				{ "name": "PTemp_C_Max", "unit": "Deg C", "prc": "Max", "type": "Num(5,2)",     "plotgrp": "PTemp" },
				{ "name": "PTemp_C_TMx",                  "prc": "TMx", "type": "TimestampNoTz" }
			]
		},
		"Hourly": {
			"columns": [
				{ "name": "TIMESTAMP",   "unit": "TS",                  "type": "TimestampNoTz"              },
				{ "name": "RECORD",      "unit": "RN",                  "type": "NonNegInt"                  },
				{ "name": "BattV_Min",   "unit": "Volts", "prc": "Min", "type": "Num(4,2)"                   },
				{ "name": "PTemp_C_Min", "unit": "Deg C", "prc": "Min", "type": "Num(5,2)",      "plotgrp": "PTemp" },
				{ "name": "PTemp_C_Max", "unit": "Deg C", "prc": "Max", "type": "Num(5,2)",      "plotgrp": "PTemp" },
				{ "name": "AirT_C(42)",  "unit": "Deg C", "prc": "Smp", "type": "Num(5,2)",      "var":"abc", "sens": "acme532", "desc": "air temperature single sample only" },
				{ "name": "AirT_C_Avg",  "unit": "Deg C", "prc": "Avg", "type": "Num(5,2)",      "var":"def", "sens": "acme532", "desc": "air temperature average over sampling period" },
				{ "name": "RelHumid",    "unit": "%",     "prc": "Smp", "type": "Num(5,2)",                   "sens": "acme42" },
				{ "name": "BP_mbar_Avg", "unit": "mbar",  "prc": "Avg", "type": "Num(7,3)",      "var":"def", "sens": "acme42" }
			],
			"mappings": {
				"Press_Humid": {
					"type": "view",
					"map": [
						{
							"old": { "name": "TIMESTAMP",   "unit": "TS"                  },
							"new": { "name": "Timestamp"                                  }
						},
						{
							"old": { "name": "BP_mbar_Avg", "unit": "mbar",  "prc": "Avg" },
							"new": { "name": "BPress_Avg",  "unit": "mbar",  "prc": "Avg" }
						}, {
							"old": { "name": "RelHumid",    "unit": "%",     "prc": "Smp" },
							"new": { "name": "RH_Smp",      "unit": "%",     "prc": "Smp" }
						}
					]
				}
			}
		}
	}
}
